# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmInfo', '0015_auto_20160219_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='img',
            field=models.ImageField(default=b'pics/default.jpeg', upload_to=b'pics'),
        ),
    ]
