# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmInfo', '0019_auto_20160406_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='zip_code',
            field=models.CharField(default=17013, max_length=5),
            preserve_default=False,
        ),
    ]
